/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Localizacao;
import Model.Registros;
import java.awt.Component;
import java.awt.geom.Point2D;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.jxmapviewer.viewer.DefaultWaypoint;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.Waypoint;
import org.jxmapviewer.viewer.WaypointPainter;

/**
 *
 * @author Ericp
 */
public class frmAgente extends javax.swing.JFrame {
Registros reg = new Registros();
public double latitude;
public double longitude;

    public frmAgente(double latitude, double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public void SalvarCoords(){
        System.out.println(getLatitude());
    }
    /**
     * Creates new form frmAgente
     */
    public frmAgente() {
        initComponents();
      
         mapa1.init();
         GeoPosition centro = new GeoPosition(-24.49609687511922, -47.846299351792965); // Coordenadas de São Paulo
        mapa1.setAddressLocation(centro);
        mapa1.setZoom(4);
           List<Localizacao> listaLocalizacoes = reg.carregarLocalizacoes();

         
        // Cria waypoints a partir das localizações
        Set<Waypoint> waypoints = new HashSet<>();
        for (Localizacao loc : listaLocalizacoes) {
            GeoPosition posicao = new GeoPosition(loc.getLatitude(), loc.getLongitude());
            waypoints.add(new DefaultWaypoint(posicao));
        }
           
           
        WaypointPainter<Waypoint> waypointPainter = new WaypointPainter<>();
        waypointPainter.setWaypoints(waypoints);
        mapa1.setOverlayPainter(waypointPainter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLat = new javax.swing.JTextField();
        lblLon = new javax.swing.JTextField();
        mapa1 = new Model.Mapa();
        epidemix_menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_point = new javax.swing.JLabel();

        lblLat.setText("jTextField1");
        lblLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLatActionPerformed(evt);
            }
        });

        lblLon.setText("jTextField1");
        lblLon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapa1MouseClicked(evt);
            }
        });

        epidemix_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icon_epidemix_red.png"))); // NOI18N
        epidemix_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epidemix_menuMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/gps_first_point.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        txt_point.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/pin.png"))); // NOI18N
        txt_point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pointMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mapa1Layout = new javax.swing.GroupLayout(mapa1);
        mapa1.setLayout(mapa1Layout);
        mapa1Layout.setHorizontalGroup(
            mapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapa1Layout.createSequentialGroup()
                        .addGap(0, 126, Short.MAX_VALUE)
                        .addComponent(txt_point)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(mapa1Layout.createSequentialGroup()
                        .addComponent(epidemix_menu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mapa1Layout.setVerticalGroup(
            mapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(epidemix_menu)
                .addGap(38, 606, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapa1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mapa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txt_point))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapa1MouseClicked
        // TODO add your handling code here:
        Point2D pontoPixel = evt.getPoint();

   
       //recebe o valor dos pixels. teste de click
        GeoPosition geoPos = mapa1.getTileFactory().pixelToGeo(pontoPixel, mapa1.getZoom());
             // Converte o ponto em pixels para uma coordenada geográfica
         GeoPosition geoPosition = mapa1.convertPointToGeoPosition(pontoPixel);

        // Exibe a latitude e a longitude no console ou use conforme necessário
        System.out.println("Lat: "+ geoPosition.getLatitude());
        System.out.println("Latitude: " + geoPos.getLatitude() + ", Longitude: " + geoPos.getLongitude());
BigDecimal lat = new BigDecimal(geoPosition.getLatitude()).setScale(7, RoundingMode.HALF_UP);
BigDecimal lon = new BigDecimal(geoPosition.getLongitude()).setScale(7, RoundingMode.HALF_UP);
setLatitude(lat.doubleValue());
setLongitude(lon.doubleValue());
lblLat.setText(""+ getLatitude());
lblLon.setText(""+ getLongitude());

    }//GEN-LAST:event_mapa1MouseClicked

    private void lblLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLatActionPerformed

    private void lblLonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLonActionPerformed

    private void epidemix_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_epidemix_menuMouseClicked
        frmPopup popup = new frmPopup();
        new frmPopup().setVisible(true);
        popup.setVerificar(1);
    }//GEN-LAST:event_epidemix_menuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        GeoPosition centro = new GeoPosition(-24.49609687511922, -47.846299351792965);
        mapa1.setAddressLocation(centro);
        mapa1.setZoom(4);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_pointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pointMouseClicked
        frmcadRegistros frmCad = new frmcadRegistros();
        frmCad.setVisible(true);
        frmCad.lblLat.setText(""+getLatitude());
        frmCad.lblLon.setText(""+getLongitude());
    }//GEN-LAST:event_txt_pointMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel epidemix_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lblLat;
    private javax.swing.JTextField lblLon;
    private Model.Mapa mapa1;
    private javax.swing.JLabel txt_point;
    // End of variables declaration//GEN-END:variables
}
